-- AlterTable
ALTER TABLE "Review"
ADD COLUMN "displayName" TEXT,
ADD COLUMN "headline" TEXT,
ADD COLUMN "isCarouselVisible" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
